// Vercel Serverless Function: GET /api/participants
const PARTICIPANTS = [
  {
    "kode": "SMB-001",
    "nama": "Budi Santoso",
    "panggilan": "Budi",
    "disc": "D/I",
    "mbti": "ENFP",
    "kursi": 1,
    "kamar": "107",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-015",
    "nama": "Siti Rahma",
    "panggilan": "Siti",
    "disc": "C/S",
    "mbti": "ISTJ",
    "kursi": 2,
    "kamar": "102",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-010",
    "nama": "Andi Wijaya",
    "panggilan": "Andi",
    "disc": "D/I",
    "mbti": "INFP",
    "kursi": 3,
    "kamar": "105",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-003",
    "nama": "Dewi Lestari",
    "panggilan": "Dewi",
    "disc": "I/S",
    "mbti": "ISFJ",
    "kursi": 4,
    "kamar": "111",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-008",
    "nama": "Eka Pratama",
    "panggilan": "Eka",
    "disc": "D/C",
    "mbti": "INFP",
    "kursi": 5,
    "kamar": "104",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-014",
    "nama": "Fajar Hidayat",
    "panggilan": "Fajar",
    "disc": "I/D",
    "mbti": "ENFP",
    "kursi": 6,
    "kamar": "101",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-004",
    "nama": "Gita Gutawa",
    "panggilan": "Gita",
    "disc": "D/I",
    "mbti": "ESTP",
    "kursi": 7,
    "kamar": "108",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-011",
    "nama": "Hendra Setiawan",
    "panggilan": "Hendra",
    "disc": "S/C",
    "mbti": "INFP",
    "kursi": 8,
    "kamar": "109",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-007",
    "nama": "Oscar Perdana",
    "panggilan": "Oscar",
    "disc": "I/S",
    "mbti": "ESFJ",
    "kursi": 9,
    "kamar": "108",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-FADLI",
    "nama": "Lead Trainer",
    "panggilan": "Trainer",
    "disc": "S",
    "mbti": "Trainer",
    "kursi": 10,
    "kamar": "-",
    "gender": "Laki-laki",
    "peran": "Lead Trainer & Facilitator",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-006",
    "nama": "Kartika Sari",
    "panggilan": "Kartika",
    "disc": "D/C",
    "mbti": "ESFP",
    "kursi": 11,
    "kamar": "110",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-012",
    "nama": "Lukman Hakim",
    "panggilan": "Lukman",
    "disc": "C/S",
    "mbti": "ISTP",
    "kursi": 12,
    "kamar": "110",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-020",
    "nama": "Maya Anggraini",
    "panggilan": "Maya",
    "disc": "D/I",
    "mbti": "ISTP",
    "kursi": 13,
    "kamar": "103",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-BUF14",
    "nama": "Empty / Buffer Seat",
    "panggilan": "Buffer",
    "disc": "-",
    "mbti": "-",
    "kursi": 14,
    "kamar": "-",
    "gender": "-",
    "peran": "Kursi Cadangan / Empty Seat",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-005",
    "nama": "Novi Saputra",
    "panggilan": "Novi",
    "disc": "D/I",
    "mbti": "ENFP",
    "kursi": 15,
    "kamar": "106",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-013",
    "nama": "Indah Permata",
    "panggilan": "Indah",
    "disc": "I/C",
    "mbti": "INFP",
    "kursi": 16,
    "kamar": "107",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-022",
    "nama": "Putra Ramadhan",
    "panggilan": "Putra",
    "disc": "D/I",
    "mbti": "ENTJ",
    "kursi": 17,
    "kamar": "102",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-019",
    "nama": "Rina Melati",
    "panggilan": "Rina",
    "disc": "S/C",
    "mbti": "ISFJ",
    "kursi": 18,
    "kamar": "106",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-009",
    "nama": "Setyo Wibowo",
    "panggilan": "Setyo",
    "disc": "D/I",
    "mbti": "ESTP",
    "kursi": 19,
    "kamar": "109",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-016",
    "nama": "Tania Putri",
    "panggilan": "Tania",
    "disc": "S",
    "mbti": "ISFP",
    "kursi": 20,
    "kamar": "111",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-018",
    "nama": "Utami Dewi",
    "panggilan": "Utami",
    "disc": "D/C",
    "mbti": "ESTP",
    "kursi": 21,
    "kamar": "105",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  },
  {
    "kode": "SMB-017",
    "nama": "Vicky Hermawan",
    "panggilan": "Vicky",
    "disc": "S/C",
    "mbti": "ISTP",
    "kursi": 22,
    "kamar": "103",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Profil karakter & komitmen peserta bootcamp.",
    "commStyle": "Gaya komunikasi profesional, ramah, dan terstruktur.",
    "saran": "Fokus pada pengembangan sales planning, komunikasi, dan follow-up.",
    "salesStrength": "Komunikatif, energik, dan mudah membangun koneksi dengan pelanggan.",
    "salesRisk": "Perlu menjaga konsistensi dalam eksekusi dan tindak lanjut.",
    "tipsKomunikasi": "Sampaikan poin utama secara lugas, antusias, dan berikan dorongan positif."
  }
];

module.exports = (req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  return res.status(200).json({
    event: "Sales Mastery Bootcamp 2026",
    location: "Kalyana Resort Kaliurang, Yogyakarta",
    totalParticipants: PARTICIPANTS.length,
    participants: PARTICIPANTS
  });
};
