// Vercel Serverless Function: GET /api/participants
const PARTICIPANTS = [
  {
    "kode": "SMB-001",
    "nama": "I Gusti Ayu Ananda Putri",
    "panggilan": "Nanda",
    "disc": "D/I",
    "mbti": "ENFP",
    "kursi": 1,
    "kamar": "421",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Tegas, berorientasi hasil, berani mengambil keputusan, bergerak cepat.",
    "commStyle": "Friendly, enthusiastic dan expressive.",
    "saran": "Friendly, enthusiastic dan expressive.. Tips: Fokus pada discipline, sales planning dan follow-up.",
    "salesStrength": "Enerjik, kreatif, komunikatif dan mudah membangun koneksi dengan customer.",
    "salesRisk": "Bisa kehilangan fokus atau kurang konsisten dalam execution.",
    "tipsKomunikasi": "Sampaikan poin utama secara ramah dan antusias, beri ruang apresiasi atas idenya, lalu bantu menjaga disiplin tindak lanjut."
  },
  {
    "kode": "SMB-016",
    "nama": "Sofyan Thohari",
    "panggilan": "Popan",
    "disc": "S",
    "mbti": "ISFP",
    "kursi": 2,
    "kamar": "425",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Tenang, kooperatif, sabar, menjaga hubungan baik.",
    "commStyle": "Calm, personal dan empathetic.",
    "saran": "Calm, personal dan empathetic.. Tips: Fokus pada confidence, negotiation dan closing drive.",
    "salesStrength": "Empatik, observant, fleksibel dan mampu menciptakan interaksi yang nyaman dengan customer.",
    "salesRisk": "Kurang assertive dan cenderung menghindari situasi yang terlalu konfrontatif.",
    "tipsKomunikasi": "Bicara dengan nada tenang, hangat, dan empati. Berikan waktu untuk mencerna informasi dan hindari pendekatan yang menekan."
  },
  {
    "kode": "SMB-010",
    "nama": "Sri Wijayati",
    "panggilan": "Jay",
    "disc": "D/I",
    "mbti": "INFP",
    "kursi": 3,
    "kamar": "413",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Assertive dan influential; percaya diri menyampaikan pendapat dan mengejar hasil.",
    "commStyle": "Soft, personal dan consultative.",
    "saran": "Soft, personal dan consultative.. Tips: Dorong assertiveness, objection handling dan closing confidence.",
    "salesStrength": "Empatik, thoughtful, genuine dan mampu memahami perspektif customer.",
    "salesRisk": "Cenderung overthinking dan kurang nyaman menghadapi rejection atau konflik.",
    "tipsKomunikasi": "Bicara secara konsultatif dan apresiatif. Sampaikan ide secara percaya diri sambil mendengarkan masukannya secara empati."
  },
  {
    "kode": "SMB-003",
    "nama": "Elfasa Khoirumansyah",
    "panggilan": "Elfasa",
    "disc": "I/S",
    "mbti": "ISFJ",
    "kursi": 4,
    "kamar": "425",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Komunikatif, approachable, kooperatif, nyaman membangun hubungan.",
    "commStyle": "Ramah, supportive dan personal.",
    "saran": "Ramah, supportive dan personal.. Tips: Fokus pada confidence, negotiation dan closing technique.",
    "salesStrength": "Relationship builder, loyal, attentive dan mampu memberikan customer experience yang baik.",
    "salesRisk": "Kurang assertive ketika harus melakukan negotiation atau closing.",
    "tipsKomunikasi": "Gunakan pendekatan ramah, kooperatif, dan penuh dukungan. Berikan rasa aman dan ajak berdiskusi tanpa konfrontasi."
  },
  {
    "kode": "SMB-008",
    "nama": "Maria Dita Fivtiari",
    "panggilan": "Dita",
    "disc": "D/C",
    "mbti": "INFP",
    "kursi": 5,
    "kamar": "412",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Kuat pada hasil, dengan perhatian terhadap standar dan kualitas.",
    "commStyle": "Personal, warm dan consultative.",
    "saran": "Personal, warm dan consultative.. Tips: Perkuat assertiveness dan keberanian menghadapi objection.",
    "salesStrength": "Empatik, genuine, mampu memahami kebutuhan customer dan membangun trust.",
    "salesRisk": "Sensitif terhadap rejection dan cenderung menghindari konflik.",
    "tipsKomunikasi": "Bicara secara personal dan hangat. Sampaikan data yang jelas serta hargai perhatiannya terhadap standar dan kualitas kerja."
  },
  {
    "kode": "SMB-007",
    "nama": "Okki Putri Fadilah",
    "panggilan": "Okki",
    "disc": "I/S",
    "mbti": "ESFJ",
    "kursi": 6,
    "kamar": "422",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Interpersonal-oriented, komunikatif, menjaga hubungan baik.",
    "commStyle": "Friendly, supportive dan engaging.",
    "saran": "Friendly, supportive dan engaging.. Tips: Tingkatkan assertiveness, negotiation dan handling difficult customers.",
    "salesStrength": "Warm, communicative, relationship-oriented dan kuat dalam membangun customer trust.",
    "salesRisk": "Terlalu mempertimbangkan respons orang lain dan kurang nyaman dengan konflik.",
    "tipsKomunikasi": "Gunakan bahasa yang ramah, bersahabat, dan mendukung. Libatkan dalam percakapan positif dan ciptakan suasana yang nyaman."
  },
  {
    "kode": "SMB-004",
    "nama": "Nindy Amalia",
    "panggilan": "Nindy",
    "disc": "D/I",
    "mbti": "ESTP",
    "kursi": 7,
    "kamar": "422",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Sangat berorientasi hasil, berani, kompetitif, dan persistent.",
    "commStyle": "Direct, energetic dan persuasive.",
    "saran": "Direct, energetic dan persuasive.. Tips: Fokus pada consultative questioning dan active listening.",
    "salesStrength": "Confident, competitive, action-oriented dan cepat mengambil keputusan.",
    "salesRisk": "Bisa terlalu cepat masuk ke solusi tanpa cukup menggali kebutuhan customer.",
    "tipsKomunikasi": "Bicara secara langsung, lugas, dan energik. Fokus pada solusi cepat dan ajak berdiskusi secara interaktif."
  },
  {
    "kode": "SMB-011",
    "nama": "Paramitha Maharesmi Nugraheni Putri",
    "panggilan": "Mitha",
    "disc": "S/C",
    "mbti": "INFP",
    "kursi": 8,
    "kamar": "421",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Stabil, hati-hati, cukup terstruktur dan balanced.",
    "commStyle": "Soft, personal dan persuasive secara natural.",
    "saran": "Soft, personal dan persuasive secara natural.. Tips: Dorong keberanian untuk ask for the sale dan menghadapi rejection.",
    "salesStrength": "Empatik, kreatif, mampu membangun koneksi berdasarkan kebutuhan dan nilai customer.",
    "salesRisk": "Cenderung menghindari situasi konfrontatif dan dapat terlalu idealis.",
    "tipsKomunikasi": "Bicara dengan nada lembut dan personal. Dengarkan dengan baik dan bantu memberikan dorongan positif saat mengambil keputusan."
  },
  {
    "kode": "SMB-014",
    "nama": "Fuad Jaka Pamungkas",
    "panggilan": "Jaka",
    "disc": "I/D",
    "mbti": "ENFP",
    "kursi": 9,
    "kamar": "415",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Komunikatif, cukup berani, terdorong memengaruhi orang lain.",
    "commStyle": "Energetic, conversational, enthusiastic.",
    "saran": "Energetic, conversational, enthusiastic.. Tips: Gunakan sales funnel, checklist dan follow-up discipline.",
    "salesStrength": "Sangat komunikatif, enthusiastic, kreatif, mudah membangun networking dan persuasive.",
    "salesRisk": "Mudah kehilangan fokus dan kurang konsisten dalam follow-up/detail.",
    "tipsKomunikasi": "Bicara dengan semangat dan komunikatif. Bantu mengarahkan ide-ide kreatifnya ke dalam langkah eksekusi yang terstruktur."
  },
  {
    "kode": "SMB-015",
    "nama": "Dimas Wiyanarko",
    "panggilan": "Dimas",
    "disc": "C/S",
    "mbti": "ISTJ",
    "kursi": 10,
    "kamar": "416",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Sangat kuat pada struktur, ketelitian, dan konsistensi.",
    "commStyle": "Formal, jelas, faktual dan terstruktur.",
    "saran": "Formal, jelas, faktual dan terstruktur.. Tips: Latih agility, improvisation dan emotional selling.",
    "salesStrength": "Terstruktur, disiplin, reliable, teliti dan kuat dalam follow-up.",
    "salesRisk": "Bisa terlalu terpaku pada prosedur dan kurang fleksibel menghadapi customer yang unpredictable.",
    "tipsKomunikasi": "Gunakan bahasa yang formal, jelas, dan berbasis data faktual. Sampaikan informasi secara terstruktur dan berikan waktu verifikasi."
  },
  {
    "kode": "SMB-022",
    "nama": "I Gusti Putu Yaktianuraga",
    "panggilan": "Bagus",
    "disc": "D/I",
    "mbti": "ENTJ",
    "kursi": 11,
    "kamar": "416",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Tegas, ambisius, optimis, mandiri, suka tantangan, dan persuasive.",
    "commStyle": "Direct, confident, strategic dan result-oriented.",
    "saran": "Direct, confident, strategic dan result-oriented.. Tips: Tantang untuk listen more, ask more, tell less agar tidak terlalu cepat mengarahkan customer.",
    "salesStrength": "Strong leadership, decisive, strategic, confident dan sangat target-oriented.",
    "salesRisk": "Bisa terlalu dominan, impatient dan terlalu fokus pada hasil dibandingkan relationship.",
    "tipsKomunikasi": "Bicara secara langsung, lugas, berorientasi hasil, dan strategis. Dengarkan sudut pandangnya sebelum memberikan rekomendasi."
  },
  {
    "kode": "SMB-012",
    "nama": "Yulia Mekar Rini",
    "panggilan": "Yulia",
    "disc": "C/S",
    "mbti": "ISTP",
    "kursi": 12,
    "kamar": "424",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Teliti, sistematis, hati-hati, membutuhkan kejelasan.",
    "commStyle": "Direct, factual dan solution-oriented.",
    "saran": "Direct, factual dan solution-oriented.. Tips: Perkuat rapport building, probing dan storytelling.",
    "salesStrength": "Practical problem solver, analytical, mandiri dan mampu mencari solusi dengan cepat.",
    "salesRisk": "Cenderung reserved dan dapat kurang aktif membangun emotional connection dengan customer.",
    "tipsKomunikasi": "Bicara secara to the point, faktual, dan berfokus pada solusi praktis. Hindari basa-basi berlebih dan tekankan kejelasan logika."
  },
  {
    "kode": "SMB-020",
    "nama": "Gilang Risnantyo",
    "panggilan": "Gilang",
    "disc": "D/I",
    "mbti": "ISTP",
    "kursi": 13,
    "kamar": "414",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Berorientasi hasil, tegas, proaktif, percaya diri, menyukai tantangan.",
    "commStyle": "Direct, factual dan solution-oriented.",
    "saran": "Direct, factual dan solution-oriented.. Tips: Dorong kemampuan rapport building dan probing questions.",
    "salesStrength": "Problem solver, praktis, fleksibel dan mampu tetap tenang menghadapi masalah customer.",
    "salesRisk": "Bisa kurang ekspresif dan kurang aktif dalam relationship building.",
    "tipsKomunikasi": "Bicara secara efektif, faktual, dan solusi-oriented. Sampaikan poin utama dengan jelas dan ajak berdiskusi secara praktis."
  },
  {
    "kode": "SMB-019",
    "nama": "Linda Susanto",
    "panggilan": "Linda",
    "disc": "S/C",
    "mbti": "ISFJ",
    "kursi": 14,
    "kamar": "423",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Tenang, stabil, kooperatif, menjaga hubungan, nyaman dengan struktur.",
    "commStyle": "Warm, polite dan relationship-oriented.",
    "saran": "Warm, polite dan relationship-oriented.. Tips: Fokus pada assertiveness, negotiation dan closing confidence.",
    "salesStrength": "Attentive, reliable, supportive dan mampu membangun hubungan jangka panjang dengan customer.",
    "salesRisk": "Kurang nyaman dengan rejection dan aggressive selling.",
    "tipsKomunikasi": "Bicara dengan hangat, sopan, dan komunikatif. Berikan dukungan penuh dan tekankan nilai kerjasama jangka panjang."
  },
  {
    "kode": "SMB-005",
    "nama": "Irvani Putri",
    "panggilan": "Irvani",
    "disc": "D/I",
    "mbti": "ENFP",
    "kursi": 15,
    "kamar": "423",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Aktif, memiliki drive terhadap hasil, nyaman menyampaikan pendapat.",
    "commStyle": "Energetic, friendly dan engaging.",
    "saran": "Energetic, friendly dan engaging.. Tips: Berikan struktur pipeline management dan follow-up discipline.",
    "salesStrength": "Persuasive, enthusiastic, kreatif dan kuat dalam membangun networking.",
    "salesRisk": "Mudah terdistraksi dan kurang menyukai pekerjaan yang repetitif.",
    "tipsKomunikasi": "Gunakan komunikasi yang energik dan bersahabat. Sampaikan target dengan jelas dan bantu menyusun alur kerja yang rapi."
  },
  {
    "kode": "SMB-013",
    "nama": "Ainur Hasanah",
    "panggilan": "Ainur",
    "disc": "I/C",
    "mbti": "INFP",
    "kursi": 16,
    "kamar": "417",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Komunikatif/influential dengan perhatian terhadap detail.",
    "commStyle": "Personal, hangat, thoughtful dan relationship-oriented.",
    "saran": "Personal, hangat, thoughtful dan relationship-oriented.. Tips: Latih assertiveness, objection handling dan closing melalui role play bertahap.",
    "salesStrength": "Empatik, mampu memahami kebutuhan customer, genuine dalam membangun hubungan dan memiliki pendekatan yang personal.",
    "salesRisk": "Kurang nyaman dengan rejection, konflik, atau aggressive closing.",
    "tipsKomunikasi": "Bicara secara personal, hangat, dan penuh perhatian. Dengarkan posisinya dan sampaikan masukan secara halus serta terstruktur."
  },
  {
    "kode": "SMB-006",
    "nama": "Mya Mar'atus Sholikhah",
    "panggilan": "Mya",
    "disc": "D/C",
    "mbti": "ESFP",
    "kursi": 17,
    "kamar": "424",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Berorientasi hasil sekaligus memastikan pekerjaan dilakukan dengan baik.",
    "commStyle": "Expressive, warm, engaging dan enthusiastic.",
    "saran": "Expressive, warm, engaging dan enthusiastic.. Tips: Manfaatkan kekuatan interpersonalnya, sambil memperkuat planning dan follow-up discipline.",
    "salesStrength": "Sociable, energik, friendly, spontan dan customer-oriented.",
    "salesRisk": "Mudah terdistraksi dan dapat kurang konsisten dalam administrasi/follow-up.",
    "tipsKomunikasi": "Bicara secara ekspresif, hangat, dan antusias. Apresiasi hasil kerjanya dan bantu menjaga konsistensi rencana kegiatan."
  },
  {
    "kode": "SMB-017",
    "nama": "Adiel Priyarama",
    "panggilan": "Adiel",
    "disc": "S/C",
    "mbti": "ISTP",
    "kursi": 18,
    "kamar": "414",
    "gender": "Laki-laki",
    "peran": "Peserta Bootcamp",
    "karakter": "Stabil, terstruktur, mempertimbangkan sesuatu sebelum bertindak.",
    "commStyle": "Singkat, to the point, berbasis fakta dan solusi.",
    "saran": "Singkat, to the point, berbasis fakta dan solusi.. Tips: Berikan case study dan simulasi problem solving; dorong untuk lebih aktif menggali kebutuhan customer.",
    "salesStrength": "Praktis, cepat membaca masalah, tenang menghadapi situasi sulit, dan mampu mencari solusi secara langsung.",
    "salesRisk": "Bisa kurang ekspresif dan kurang aktif membangun relationship secara verbal.",
    "tipsKomunikasi": "Bicara secara singkat, lugas, berbasis fakta, dan berfokus pada pemecahan masalah praktis secara langsung."
  },
  {
    "kode": "SMB-009",
    "nama": "Etik Andriyanti",
    "panggilan": "Andri",
    "disc": "D/I",
    "mbti": "ESTP",
    "kursi": 19,
    "kamar": "417",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Action-oriented, berani mengambil keputusan, cukup komunikatif.",
    "commStyle": "Direct, energetic, persuasive dan spontan.",
    "saran": "Direct, energetic, persuasive dan spontan.. Tips: Tekankan listening before pitching dan pentingnya sales planning.",
    "salesStrength": "Berani, energik, cepat mengambil tindakan, adaptif dan nyaman menghadapi situasi yang dinamis.",
    "salesRisk": "Dapat terlalu cepat bertindak, kurang sabar dan melewatkan detail.",
    "tipsKomunikasi": "Bicara secara spontan, energik, dan meyakinkan. Imbangi dengan kesabaran mendengarkan sebelum menyimpulkan."
  },
  {
    "kode": "SMB-018",
    "nama": "Kensrie Diah Ayuningtyas",
    "panggilan": "Kensrie",
    "disc": "D/C",
    "mbti": "ESTP",
    "kursi": 20,
    "kamar": "413",
    "gender": "Perempuan",
    "peran": "Peserta Bootcamp",
    "karakter": "Balanced antara orientasi hasil dan kebutuhan kualitas/struktur.",
    "commStyle": "Direct, spontaneous dan energetic.",
    "saran": "Direct, spontaneous dan energetic.. Tips: Latih active listening, probing dan structured selling.",
    "salesStrength": "Berani, cepat bertindak, confident, adaptif dan kompetitif.",
    "salesRisk": "Impulsif dan dapat kurang memperhatikan detail atau proses.",
    "tipsKomunikasi": "Bicara secara langsung, dinamis, dan energik. Sampaikan poin penting secara terstruktur dan dorong diskusi aktif."
  }
];

module.exports = (req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  return res.status(200).json({
    event: "Sales Mastery Bootcamp 2026",
    location: "Kalyana Resort Kaliurang, Yogyakarta",
    totalParticipants: PARTICIPANTS.length,
    participants: PARTICIPANTS
  });
};
